### ISSUE TITLE
USER STORY: Get information on community run locations

### ISSUE THREAD

**Issue by renatalantos** [renatalantos/Django-blog-project#4]
As a **runner** I can **look up running location** so that **I can join in community run**

### Acceptance criteria

- Insert map with pinned locations
- Add directions 
- Add transport methods to get there, including walking

### Tasks

- [ ]  Create user interface

- [ ] Create HTML and CSS

- [ ] Embed Google Map link

- [ ] Using appropriate programming language (Javascript, JQuery) and APIs, pin the running location permanently on map
